# Creating some arrays

We are going to practice creating some arrays. The first method is using numpy's function, linspace:

In [3]:
import numpy as np

In [4]:
np.linspace(0, 1, 21)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95, 1.  ])

You can also use np.arange to create an array of evenly spaced values within a given interval. 

In [5]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

You can also change the step size when using arange.

In [6]:
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

You can also use np.ones to create an array full of 1's of your chosen shape, passed in using a tuple (aka, when you use parentheses).

In [7]:
np.ones((4, 2, 3))

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

### Question 1

Below we're creating arrays with different shapes. Try predicting for each if elementwise addition would work, what shape the resulting array would have, then try it out and see if you were correct. Write a comment in each cell explaining why the output had a particular shape.

In [14]:
arr_1 = np.ones((3,2))
arr_2 = np.ones((2,3))
# arr_1 + arr_2
# won't work because you can't add arrays with different shapes

In [20]:
arr_1 = np.ones((4,1,5))
arr_2 = np.ones((4,6,5))
# arr_2 + arr_2
# will be an array of (4,6,5) with all 2s

In [21]:
arr_1 = np.ones((4,1,5))
arr_2 = np.ones((4,6,1))
# arr_1 + arr_2
#will be an array of 2s with shape (4,6,5) same as above--when doing these operations with unequal shapes if a dimension is one it is
#just expanded to the non-1 dimension size with copies

In [22]:
arr_1 = np.ones((4,3,5))
arr_2 = np.ones((3,5))
# arr_1 + arr_2
#same idea as above, arr_2 is treated as (1,3,5) so it is essentially two (4,3,5) added together

In [24]:
arr_1 = np.ones((4,3,5))
arr_2 = np.ones((4,3))
# arr_1 + arr_2
#doesn't work because of unequal shapes, with values greater than 1

## Summary operations

**Note that for this cell, you need to have ex_array.npy saved in the same directory as this notebook.**

Summary operations allow you to collapse an array according to a certain summary statistic. For instance, we may want to compute the overall mean firing rate in our experimental data:

In [25]:
arr = np.load('ex_array.npy')

In [26]:
arr.mean()

0.8717270073789571

You can also specify the axis along we want to average. For instance, maybe we want to average firing rates across individual trials:

In [27]:
arr.shape

(2, 10, 50, 2000)

In [28]:
arr_across_trials = arr.mean(axis=1)

In [29]:
arr_across_trials.shape

(2, 50, 2000)

The `keepdims` argument means that you don't remove the dimensions you're averaging over, but rather set their length to 1:

In [30]:
arr_across_trials = arr.mean(axis=1, keepdims=True)

In [32]:
arr_across_trials.shape
arr_across_trials

array([[[[0.65972936, 0.68679441, 0.68199004, ..., 0.96912439,
          1.07270512, 0.84568177],
         [0.79611248, 0.99935367, 0.88531804, ..., 0.50904864,
          0.3364558 , 0.4932102 ],
         [1.00938778, 1.30849305, 0.95961269, ..., 0.67265484,
          0.94855162, 0.57360145],
         ...,
         [0.32410045, 0.60430154, 0.59851933, ..., 0.43082814,
          0.35448484, 0.60595627],
         [2.20282076, 2.10202105, 1.72845273, ..., 2.40318232,
          2.62285072, 2.47028176],
         [0.77735322, 1.2437595 , 1.09964378, ..., 1.38810799,
          1.48371474, 1.22155473]]],


       [[[0.29366721, 0.40403176, 0.32066067, ..., 1.11915401,
          0.79285423, 1.20313501],
         [0.54035301, 0.7392684 , 0.70751494, ..., 1.3894037 ,
          1.30790281, 1.4672015 ],
         [0.62631555, 0.49423944, 0.59660195, ..., 0.82260387,
          0.99906975, 0.56779008],
         ...,
         [0.60475668, 0.75494216, 0.66881441, ..., 0.33957372,
          0.47778094, 0

You can average across multiple axes as well. For instance, maybe you want to average across both trials and time:

In [33]:
arr_across_trials_and_time = arr.mean(axis=(1,3))

In [34]:
arr_across_trials_and_time.shape

(2, 50)

### Question 2

- What is the average firing rate across all neurons, times, and trials for each condition?
- (Advanced, optional.) Subtract the average firing rate per time across all neurons, trials, and conditions from the original array.

When finished, upload a screenshot of this question onto courseworks.

In [44]:
arr_avg_conditions = arr.mean(axis=(1,2,3))
arr_avg_conditions

array([0.98828779, 0.75516623])

In [40]:
arr_avg_time = arr.mean(axis=(0,1,2), keepdims=True)

array([[[[0.75394219, 0.7467053 , 0.75306342, ..., 1.05328575,
          1.06057494, 1.05752845]]]])

In [45]:
arr_time_avg_normalized = arr - arr_avg_time
arr_time_avg_normalized

array([[[[-6.47206544e-01,  1.03308132e-01, -6.86937218e-01, ...,
           1.68857127e-01,  7.93763162e-01, -1.02775690e+00],
         [ 9.91900617e-01,  2.99640155e-01,  4.41549101e-01, ...,
          -6.66290996e-01, -9.14317140e-01, -4.99859593e-01],
         [ 5.22666318e-01,  8.91114728e-01,  9.77713121e-01, ...,
          -7.84107310e-01, -1.73056193e-01, -5.60118790e-01],
         ...,
         [-6.19964506e-01, -5.84717411e-01, -3.06582819e-01, ...,
          -6.13333315e-01, -4.17980685e-01,  1.77749608e-01],
         [ 1.72170039e+00,  9.47429166e-01,  1.37111118e+00, ...,
           1.56572518e+00,  2.05189010e+00,  8.62738360e-01],
         [-2.42979930e-02,  1.30009247e+00,  6.26530162e-01, ...,
           6.88706351e-01,  1.04981507e+00, -1.58825188e-01]],

        [[ 5.68429213e-02,  1.86357122e-01, -4.93684300e-01, ...,
           2.62151594e-01,  2.35650922e-01,  1.79999393e-01],
         [-1.87196338e-01,  4.20275751e-02,  3.40472904e-01, ...,
          -5.58073623e

## Indexing

Indexing in vectors works just as in lists:

In [46]:
#ignore this cell
#initializing the vectors, matrices, and lists here.
lst_1 = [25, 20, 40, 5]
vec_1 = np.array(lst_1)

lst_1 = [
    [1, 2],
    [3, 4],
    [5, 6]
]
mat_1 = np.array(lst_1)
# ignore this cell

In [47]:
vec_1

array([25, 20, 40,  5])

In [48]:
vec_1[0]

25

For matrices and higher-dimensional arrays, a single index selects a single row:

In [ ]:
mat_1

In [49]:
mat_1[0]

array([1, 2])

In [51]:
mat_1[0][1]

2

Instead of using two brackets, you can also separate the row and column index by a comma:

In [52]:
# The following two lines of code are equivalent
print(mat_1[0][0])
print(mat_1[0,0])

1
1


### Slicing

Slicing is a useful way of extracting more than one element. In particular, `j:k` extracts the elements j,...,k-1:

In [56]:
vec = np.arange(10)
print(vec)

[0 1 2 3 4 5 6 7 8 9]


In [54]:
vec[3:7]

array([3, 4, 5, 6])

We can leave either end of the range away and it will default to the beginning and the end of the list, respectively.

In [ ]:
vec[:7]

In [ ]:
vec[3:]

In [ ]:
vec[:] # What do you think this will do?

You can therefore also use the colon to select all rows of a matrix and specific columns.

In [ ]:
mat_1

In [ ]:
mat_1[:,0]

You can add another colon to specify a step size, similarly to how you would use these three arguments in `range`.

In [ ]:
print(vec)
vec[3:7:2]

We could still leave away the beginning or the end of the slice:

In [62]:
vec[::2]

array([0, 2, 4, 6, 8])

### Question 3
Predict the output of the following commands. After every output, explain in words using a comment why that was the output. Upload a screenshot of this onto courseworks.

In [57]:
vec
#this is just the entire array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [58]:
vec[:4]
#this is the array up until the value in position 4, non-inclusive of the end value

array([0, 1, 2, 3])

In [59]:
vec[5:9:2]
#this slices from 5 to 9 in steps of 2, non-inclusive of the end value

array([5, 7])

In [60]:
vec[:7:2]
#this is similar to the one above but starts from 0

array([0, 2, 4, 6])

In [61]:
vec[2::2]
#this is like slicing from 2 to the end of the array, in steps of 2

array([2, 4, 6, 8])

### Boolean indexing

Do you remember how to create an array that is true if and only if `vec` is smaller than 5?

In [63]:
vec = np.arange(10)
vec

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [64]:
selector = vec <= 5
selector

array([ True,  True,  True,  True,  True,  True, False, False, False,
       False])

You can use these boolean arrays to subset the corresponding true values.

In [65]:
vec

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [66]:
vec[selector]

array([0, 1, 2, 3, 4, 5])

In [67]:
vec[vec<=5]

array([0, 1, 2, 3, 4, 5])

You can do the same with matrices:

In [ ]:
mat_1 = np.array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
mat_1 >= 3

In [ ]:
mat_1[mat_1 >= 3]

### Questions 4
- Consider the example matrix from above and subset all entries with values between 2 and 4. You can try to do this in one line or do it through multiple lines! Upload a screenshot onto courseworks once you are done!

In [77]:
vec[(vec>=2) & (vec <= 4)]

array([2, 3, 4])